### ISSUE TITLE
Two diagrams with the name "System Landscape diagram for Legal Aid Agency"

### ISSUE THREAD

**Issue by adrianclay** [ministryofjustice/laa-architecture-as-code#68]
When I look at [structurizer I see two diagrams](https://structurizr.com/share/55246/diagrams) with the above name.

There is a sub-title which does differentiate them, but it wasn't immediately clear.

What I'm looking at:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/976274/101334741-2d27ae80-3870-11eb-9c76-c22f58f14932.png">

**Comment by richrace** [comment]
I think it's this line we need to change:

https://github.com/ministryofjustice/laa-architecture-as-code/blob/main/src/main/kotlin/defineFilteredViews.kt#L8
